

### 게임 관련 설정 ###
Clearing inventory: true
Providing item in sky-block: true
Removing entities: true
Ignoring bed: true

### 월드 관련 설정 ###
Auto save: true
Spawning animals: false
Spawning monsters: false
Difficulty: 1

### 기타 설정 ###
Fast start: true
Allowing gambling: true
Increasing ability lottery number: false
